"""属性类型解析函数 — 全部从 _all_types.py 导出（向后兼容层）。

通过扁平导出（per D-03），调用者使用：
    from uasset_read.parsers.property_types import parse_bool_property, parse_int_property, ...
"""

# 从实际的实现文件导入所有内容
from uasset_read.parsers.property_types._all_types import *  # noqa: F401, F403

# 显式重新导出以支持 __all__ 和 IDE 补全
from uasset_read.parsers.property_types._all_types import (  # noqa: F401
    get_struct_size,
    parse_bool_property,
    parse_int_property,
    parse_uint16_property,
    parse_uint32_property,
    parse_uint64_property,
    parse_float_property,
    parse_double_property,
    parse_str_property,
    parse_utf8_str_property,
    parse_ansi_str_property,
    parse_name_property,
    parse_enum_property,
    parse_guid_property,
    parse_object_property,
    parse_soft_object_property,
    parse_weak_object_property,
    parse_lazy_object_property,
    parse_class_property,
    parse_soft_class_property,
    parse_asset_object_property,
    parse_interface_property,
    parse_array_property,
    parse_struct_property,
    parse_map_property,
    parse_set_property,
    parse_text_property,
    parse_delegate_property,
    parse_multicast_delegate_property,
    parse_multicast_inline_delegate_property,
    parse_multicast_sparse_delegate_property,
    parse_field_path_property,
    parse_optional_property,
    parse_verse_string_property,
    parse_verse_class_property,
    parse_verse_function_property,
    parse_verse_dynamic_property,
    parse_verse_cell_property,
    parse_verse_value_property,
    _extract_struct_type_from_tag,
    _extract_map_types_from_tag,
    _extract_set_type_from_tag,
    _extract_enum_type_from_tag,
)

__all__ = [
    "get_struct_size",
    "parse_bool_property",
    "parse_int_property",
    "parse_uint16_property",
    "parse_uint32_property",
    "parse_uint64_property",
    "parse_float_property",
    "parse_double_property",
    "parse_str_property",
    "parse_utf8_str_property",
    "parse_ansi_str_property",
    "parse_name_property",
    "parse_enum_property",
    "parse_guid_property",
    "parse_object_property",
    "parse_soft_object_property",
    "parse_weak_object_property",
    "parse_lazy_object_property",
    "parse_class_property",
    "parse_soft_class_property",
    "parse_asset_object_property",
    "parse_interface_property",
    "parse_array_property",
    "parse_struct_property",
    "parse_map_property",
    "parse_set_property",
    "parse_text_property",
    "parse_delegate_property",
    "parse_multicast_delegate_property",
    "parse_multicast_inline_delegate_property",
    "parse_multicast_sparse_delegate_property",
    "parse_field_path_property",
    "parse_optional_property",
    "parse_verse_string_property",
    "parse_verse_class_property",
    "parse_verse_function_property",
    "parse_verse_dynamic_property",
    "parse_verse_cell_property",
    "parse_verse_value_property",
    "_extract_struct_type_from_tag",
    "_extract_map_types_from_tag",
    "_extract_set_type_from_tag",
    "_extract_enum_type_from_tag",
]
