"""K2Node 类型静态数据 — 从 UE5.8 源码提取。

供 N2CNodeTypeRegistry 和 N2CNodeType 枚举使用。
数据来源：UE5.8 Engine/Source/Editor/
  - BlueprintGraph/Classes + Private
  - AnimGraph/Public
  - AIGraph/Public
  - UMGEditor/Classes + Private/Nodes
  - MovieSceneTools/Public
  - GameplayTasksEditor/Classes

总计 122 种类型（121 条继承关系，K2Node 为根节点无父类）。
"""
from __future__ import annotations

# class_name → 语义类型枚举名映射（122 种）
# 特殊映射已标注（如 K2Node_IfThenElse → Branch）
K2NODE_ENUM_NAMES: dict[str, str] = {
    "K2Node": "K2NodeBase",
    "K2Node_AIMoveTo": "AIMoveTo",
    "K2Node_ActorBoundEvent": "ActorBoundEvent",
    "K2Node_AddComponent": "AddComponent",
    "K2Node_AddComponentByClass": "AddComponentByClass",
    "K2Node_AddDelegate": "AddDelegate",
    "K2Node_AnimGetter": "AnimGetter",
    "K2Node_AnimNodeReference": "AnimNodeReference",
    "K2Node_AssignDelegate": "AssignDelegate",
    "K2Node_AssignmentStatement": "AssignmentStatement",
    "K2Node_AsyncAction": "AsyncAction",
    "K2Node_BaseAsyncTask": "BaseAsyncTask",
    "K2Node_BaseMCDelegate": "BaseMCDelegate",
    "K2Node_BitmaskLiteral": "BitmaskLiteral",
    "K2Node_BreakStruct": "BreakStruct",
    "K2Node_CallArrayFunction": "CallArrayFunction",
    "K2Node_CallDataTableFunction": "CallDataTableFunction",
    "K2Node_CallDelegate": "CallDelegate",
    "K2Node_CallFunction": "CallFunction",
    "K2Node_CallFunctionOnMember": "CallFunctionOnMember",
    "K2Node_CallMaterialParameterCollectionFunction": "CallMaterialParameterCollectionFunction",
    "K2Node_CallParentFunction": "CallParentFunction",
    "K2Node_CastByteToEnum": "CastByteToEnum",
    "K2Node_ClassDynamicCast": "ClassDynamicCast",
    "K2Node_ClearDelegate": "ClearDelegate",
    "K2Node_CommutativeAssociativeBinaryOperator": "BinaryOperator",
    "K2Node_ComponentBoundEvent": "ComponentBoundEvent",
    "K2Node_Composite": "Composite",
    "K2Node_ConstructObjectFromClass": "ConstructObject",
    "K2Node_ConvertAsset": "ConvertAsset",
    "K2Node_Copy": "Copy",
    "K2Node_CreateDelegate": "CreateDelegate",
    "K2Node_CreateDragDropOperation": "CreateDragDropOperation",
    "K2Node_CreateWidget": "CreateWidget",
    "K2Node_CustomEvent": "CustomEvent",
    "K2Node_DeadClass": "DeadClass",
    "K2Node_DelegateSet": "DelegateSet",
    "K2Node_DoOnceMultiInput": "DoOnce",
    "K2Node_DynamicCast": "DynamicCast",
    "K2Node_EaseFunction": "EaseFunction",
    "K2Node_EditablePinBase": "EditablePinBase",
    "K2Node_EditorPropertyAccessBase": "EditorPropertyAccessBase",
    "K2Node_EnumEquality": "EnumEquality",
    "K2Node_EnumInequality": "EnumInequality",
    "K2Node_EnumLiteral": "EnumLiteral",
    "K2Node_Event": "Event",
    "K2Node_ExecutionSequence": "Sequence",
    "K2Node_ForEachElementInEnum": "ForEachEnum",
    "K2Node_FormatText": "FormatText",
    "K2Node_FunctionEntry": "FunctionEntry",
    "K2Node_FunctionResult": "FunctionResult",
    "K2Node_FunctionTerminator": "FunctionTerminator",
    "K2Node_GeneratedBoundEvent": "GeneratedBoundEvent",
    "K2Node_GenericCreateObject": "GenericCreateObject",
    "K2Node_GenericToText": "GenericToText",
    "K2Node_GetArrayItem": "GetArrayItem",
    "K2Node_GetClassDefaults": "GetClassDefaults",
    "K2Node_GetDataTableRow": "GetDataTableRow",
    "K2Node_GetEnumeratorName": "GetEnumeratorName",
    "K2Node_GetEnumeratorNameAsString": "GetEnumeratorNameAsString",
    "K2Node_GetInputAxisKeyValue": "GetInputAxisKeyValue",
    "K2Node_GetInputAxisValue": "GetInputAxisValue",
    "K2Node_GetInputVectorAxisValue": "GetInputVectorAxisValue",
    "K2Node_GetNumEnumEntries": "GetNumEnumEntries",
    "K2Node_GetSequenceBinding": "GetSequenceBinding",
    "K2Node_GetSubsystem": "GetSubsystem",
    "K2Node_IfThenElse": "Branch",           # 语义映射
    "K2Node_InputAction": "InputAction",
    "K2Node_InputActionEvent": "InputActionEvent",
    "K2Node_InputAxisEvent": "InputAxisEvent",
    "K2Node_InputAxisKeyEvent": "InputKeyEvent",
    "K2Node_InputKey": "InputKey",
    "K2Node_InputKeyEvent": "InputKeyEvent",
    "K2Node_InputTouch": "InputTouch",
    "K2Node_InputTouchEvent": "InputTouchEvent",
    "K2Node_InputVectorAxisEvent": "InputVectorAxisEvent",
    "K2Node_InstancedStruct": "InstancedStruct",
    "K2Node_Knot": "Knot",
    "K2Node_LatentGameplayTaskCall": "LatentGameplayTaskCall",
    "K2Node_Literal": "Literal",
    "K2Node_LoadAsset": "LoadAsset",
    "K2Node_MacroInstance": "MacroInstance",
    "K2Node_MakeArray": "MakeArray",
    "K2Node_MakeContainer": "MakeContainer",
    "K2Node_MakeMap": "MakeMap",
    "K2Node_MakeSet": "MakeSet",
    "K2Node_MakeStruct": "MakeStruct",
    "K2Node_MakeVariable": "MakeVariable",
    "K2Node_MapForEach": "MapForEach",
    "K2Node_MathExpression": "MathExpression",
    "K2Node_Message": "Message",
    "K2Node_MultiGate": "MultiGate",
    "K2Node_PlayAnimation": "PlayAnimation",
    "K2Node_PlayMontage": "PlayMontage",
    "K2Node_PromotableOperator": "PromotableOperator",
    "K2Node_PureAssignmentStatement": "PureAssignmentStatement",
    "K2Node_RemoveDelegate": "RemoveDelegate",
    "K2Node_Select": "Select",
    "K2Node_Self": "Self",
    "K2Node_SetFieldsInStruct": "SetFieldsInStruct",
    "K2Node_SetForEach": "SetForEach",
    "K2Node_SetVariableOnPersistentFrame": "SetVariableOnPersistentFrame",
    "K2Node_SpawnActor": "SpawnActor",
    "K2Node_SpawnActorFromClass": "SpawnActorFromClass",
    "K2Node_StructMemberGet": "StructMemberGet",
    "K2Node_StructMemberSet": "StructMemberSet",
    "K2Node_StructOperation": "StructOperation",
    "K2Node_Switch": "Switch",
    "K2Node_SwitchEnum": "SwitchEnum",
    "K2Node_SwitchInteger": "SwitchInt",     # 语义映射
    "K2Node_SwitchName": "SwitchName",
    "K2Node_SwitchString": "SwitchString",
    "K2Node_TemporaryVariable": "TemporaryVariable",
    "K2Node_Timeline": "Timeline",
    "K2Node_TransitionRuleGetter": "TransitionRuleGetter",
    "K2Node_Tunnel": "Tunnel",
    "K2Node_TunnelBoundary": "TunnelBoundary",
    "K2Node_Variable": "Variable",
    "K2Node_VariableGet": "VariableGet",
    "K2Node_VariableSet": "VariableSet",
    "K2Node_VariableSetRef": "VariableSetRef",
    "K2Node_WidgetAnimationEvent": "WidgetAnimationEvent",
}

# class_name → parent_class_name 继承关系映射（121 条）
# K2Node 为根节点，不在本映射中
K2NODE_INHERITANCE: dict[str, str] = {
    "K2Node_ActorBoundEvent": "K2Node_Event",
    "K2Node_AddComponent": "K2Node_CallFunction",
    "K2Node_AddComponentByClass": "K2Node_ConstructObjectFromClass",
    "K2Node_AddDelegate": "K2Node_BaseMCDelegate",
    "K2Node_AIMoveTo": "K2Node_BaseAsyncTask",
    "K2Node_AnimGetter": "K2Node_CallFunction",
    "K2Node_AnimNodeReference": "K2Node",
    "K2Node_AssignDelegate": "K2Node_AddDelegate",
    "K2Node_AssignmentStatement": "K2Node",
    "K2Node_AsyncAction": "K2Node_BaseAsyncTask",
    "K2Node_BaseAsyncTask": "K2Node",
    "K2Node_BaseMCDelegate": "K2Node",
    "K2Node_BitmaskLiteral": "K2Node",
    "K2Node_BreakStruct": "K2Node_StructOperation",
    "K2Node_CallArrayFunction": "K2Node_CallFunction",
    "K2Node_CallDataTableFunction": "K2Node_CallFunction",
    "K2Node_CallDelegate": "K2Node_BaseMCDelegate",
    "K2Node_CallFunction": "K2Node",
    "K2Node_CallFunctionOnMember": "K2Node_CallFunction",
    "K2Node_CallMaterialParameterCollectionFunction": "K2Node_CallFunction",
    "K2Node_CallParentFunction": "K2Node_CallFunction",
    "K2Node_CastByteToEnum": "K2Node",
    "K2Node_ClassDynamicCast": "K2Node_DynamicCast",
    "K2Node_ClearDelegate": "K2Node_BaseMCDelegate",
    "K2Node_CommutativeAssociativeBinaryOperator": "K2Node_CallFunction",
    "K2Node_ComponentBoundEvent": "K2Node_Event",
    "K2Node_Composite": "K2Node_Tunnel",
    "K2Node_ConstructObjectFromClass": "K2Node",
    "K2Node_ConvertAsset": "K2Node",
    "K2Node_Copy": "K2Node",
    "K2Node_CreateDelegate": "K2Node",
    "K2Node_CreateDragDropOperation": "K2Node_ConstructObjectFromClass",
    "K2Node_CreateWidget": "K2Node_ConstructObjectFromClass",
    "K2Node_CustomEvent": "K2Node",
    "K2Node_DeadClass": "K2Node",
    "K2Node_DelegateSet": "K2Node_BaseMCDelegate",
    "K2Node_DoOnceMultiInput": "K2Node",
    "K2Node_DynamicCast": "K2Node",
    "K2Node_EaseFunction": "K2Node",
    "K2Node_EditablePinBase": "K2Node",
    "K2Node_EditorPropertyAccessBase": "K2Node_CallFunction",
    "K2Node_EnumEquality": "K2Node",
    "K2Node_EnumInequality": "K2Node",
    "K2Node_EnumLiteral": "K2Node",
    "K2Node_Event": "K2Node_EditablePinBase",
    "K2Node_ExecutionSequence": "K2Node",
    "K2Node_ForEachElementInEnum": "K2Node",
    "K2Node_FormatText": "K2Node",
    "K2Node_FunctionEntry": "K2Node_FunctionTerminator",
    "K2Node_FunctionResult": "K2Node_FunctionTerminator",
    "K2Node_FunctionTerminator": "K2Node_EditablePinBase",
    "K2Node_GeneratedBoundEvent": "K2Node_Event",
    "K2Node_GenericCreateObject": "K2Node",
    "K2Node_GenericToText": "K2Node",
    "K2Node_GetArrayItem": "K2Node",
    "K2Node_GetClassDefaults": "K2Node_GetSubsystem",
    "K2Node_GetDataTableRow": "K2Node",
    "K2Node_GetEnumeratorName": "K2Node",
    "K2Node_GetEnumeratorNameAsString": "K2Node_GetEnumeratorName",
    "K2Node_GetInputAxisKeyValue": "K2Node_CallFunction",
    "K2Node_GetInputAxisValue": "K2Node_CallFunction",
    "K2Node_GetInputVectorAxisValue": "K2Node_CallFunction",
    "K2Node_GetNumEnumEntries": "K2Node",
    "K2Node_GetSequenceBinding": "K2Node",
    "K2Node_GetSubsystem": "K2Node",
    "K2Node_IfThenElse": "K2Node",
    "K2Node_InputAction": "K2Node",
    "K2Node_InputActionEvent": "K2Node_Event",
    "K2Node_InputAxisEvent": "K2Node_Event",
    "K2Node_InputAxisKeyEvent": "K2Node_Event",
    "K2Node_InputKey": "K2Node",
    "K2Node_InputKeyEvent": "K2Node",
    "K2Node_InputTouch": "K2Node",
    "K2Node_InputTouchEvent": "K2Node_Event",
    "K2Node_InputVectorAxisEvent": "K2Node_Event",
    "K2Node_InstancedStruct": "K2Node_CallFunction",
    "K2Node_Knot": "K2Node",
    "K2Node_LatentGameplayTaskCall": "K2Node_BaseAsyncTask",
    "K2Node_Literal": "K2Node",
    "K2Node_LoadAsset": "K2Node",
    "K2Node_MacroInstance": "K2Node_Tunnel",
    "K2Node_MakeArray": "K2Node_MakeContainer",
    "K2Node_MakeContainer": "K2Node",
    "K2Node_MakeMap": "K2Node_MakeContainer",
    "K2Node_MakeSet": "K2Node_MakeContainer",
    "K2Node_MakeStruct": "K2Node_StructOperation",
    "K2Node_MakeVariable": "K2Node",
    "K2Node_MapForEach": "K2Node",
    "K2Node_MathExpression": "K2Node",
    "K2Node_Message": "K2Node_CallFunction",
    "K2Node_MultiGate": "K2Node_ExecutionSequence",
    "K2Node_PlayAnimation": "K2Node_BaseAsyncTask",
    "K2Node_PlayMontage": "K2Node_BaseAsyncTask",
    "K2Node_PromotableOperator": "K2Node_CallFunction",
    "K2Node_PureAssignmentStatement": "K2Node",
    "K2Node_RemoveDelegate": "K2Node_BaseMCDelegate",
    "K2Node_Select": "K2Node",
    "K2Node_Self": "K2Node",
    "K2Node_SetFieldsInStruct": "K2Node_StructMemberSet",
    "K2Node_SetForEach": "K2Node",
    "K2Node_SetVariableOnPersistentFrame": "K2Node",
    "K2Node_SpawnActor": "K2Node",
    "K2Node_SpawnActorFromClass": "K2Node_ConstructObjectFromClass",
    "K2Node_StructMemberGet": "K2Node_StructOperation",
    "K2Node_StructMemberSet": "K2Node_StructOperation",
    "K2Node_StructOperation": "K2Node_Variable",
    "K2Node_Switch": "K2Node",
    "K2Node_SwitchEnum": "K2Node_Switch",
    "K2Node_SwitchInteger": "K2Node_Switch",
    "K2Node_SwitchName": "K2Node_Switch",
    "K2Node_SwitchString": "K2Node_Switch",
    "K2Node_TemporaryVariable": "K2Node",
    "K2Node_Timeline": "K2Node",
    "K2Node_TransitionRuleGetter": "K2Node",
    "K2Node_Tunnel": "K2Node_EditablePinBase",
    "K2Node_TunnelBoundary": "K2Node",
    "K2Node_Variable": "K2Node",
    "K2Node_VariableGet": "K2Node_Variable",
    "K2Node_VariableSet": "K2Node_Variable",
    "K2Node_VariableSetRef": "K2Node_Variable",
    "K2Node_WidgetAnimationEvent": "K2Node_Event",
}

# 所有类型列表（从 K2NODE_ENUM_NAMES.keys() 派生）
K2NODE_TYPES: list[str] = list(K2NODE_ENUM_NAMES.keys())


def get_parent_chain(class_name: str) -> list[str]:
    """获取完整继承链（从 class_name 到根）。

    包含循环保护（visited set），最大深度 10。

    Args:
        class_name: K2Node 类名（如 "K2Node_CallFunction"）

    Returns:
        继承链列表，从当前类到根节点
    """
    chain = [class_name]
    current = class_name
    visited: set[str] = set()
    max_depth = 10

    while current in K2NODE_INHERITANCE and len(chain) <= max_depth:
        if current in visited:
            break  # 循环保护
        visited.add(current)
        parent = K2NODE_INHERITANCE[current]
        chain.append(parent)
        current = parent

    return chain
