"""Tests for Niagara pin deserialization GUID marker handling — Issue #545.

Covers:
- GUID marker = 0: no GUID bytes consumed, pins decode from expected offset
- GUID marker != 0: 16-byte GUID consumed before pin_count
- Pin alignment after GUID consumption
- Regression: existing Niagara sample parses correctly
"""

from __future__ import annotations

import struct
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

import pytest

from uasset_read.archive import ByteArchive
from uasset_read.parsers.asset_types.niagara_node import _decode_pins_from_tail
from uasset_read import parse_uasset_with_linker


# ---------------------------------------------------------------------------
# Mock export with required attributes for pin type reading
# ---------------------------------------------------------------------------

@dataclass
class MockPackageSummary:
    """Minimal PackageFileSummary mock for pin type reading."""
    custom_versions: list = field(default_factory=list)

    def get_custom_version(self, guid: Any, default: int = 0) -> int:
        """Return default custom version."""
        return default


@dataclass
class MockExport:
    """Minimal ObjectExport mock for pin decoding tests."""
    package_summary: MockPackageSummary = field(default_factory=MockPackageSummary)
    package_linker: Any = None
    package_import_map: Any = None
    package_export_map: Any = None


# ---------------------------------------------------------------------------
# Binary helpers
# ---------------------------------------------------------------------------

def u32(value: int) -> bytes:
    """Little-endian unsigned 32-bit integer."""
    return struct.pack("<I", value)


def i32(value: int) -> bytes:
    """Little-endian signed 32-bit integer."""
    return struct.pack("<i", value)


def u8(value: int) -> bytes:
    """Single byte."""
    return bytes([value & 0xFF])


def fname(index: int = 0, number: int = 0) -> bytes:
    """FName: index (u32) + number (u32)."""
    return u32(index) + u32(number)


def empty_ftext() -> bytes:
    """Minimal FText (None history, no culture-invariant string)."""
    return u32(0) + u8(0xFF) + u32(0)  # flags + history_type(-1) + bHasCulture=false


def empty_fstring() -> bytes:
    """Minimal FString (length=0)."""
    return i32(0)


def simple_pin_type() -> bytes:
    """Minimal FEdGraphPinType."""
    data = b""
    data += fname(0, 0)       # PinCategory
    data += fname(0, 0)       # PinSubCategory
    data += i32(0)            # PinSubCategoryObject (PackageIndex)
    data += u8(0)             # ContainerType
    data += u32(0)            # bIsReference
    data += u32(0)            # bIsWeakPointer
    # FSimpleMemberReference
    data += i32(0)            # MemberParent (PackageIndex)
    data += fname(0, 0)       # MemberName
    data += u32(0) * 4        # MemberGuid (16 bytes)
    data += u32(0)            # bIsConst
    data += u32(0)            # bIsUObjectWrapper
    data += u32(0)            # bSerializeAsSinglePrecisionFloat
    return data


def build_single_pin() -> bytes:
    """Build binary data for a single minimal UEdGraphPin record."""
    data = b""
    # --- Pin reference ---
    data += u32(0)             # bNullPtr = false
    data += i32(0)             # OwningNode (PackageIndex)
    data += u32(0) * 4         # PinId (FGuid)

    # --- Pin body ---
    data += i32(0)             # OwningNode (repeated)
    data += u32(0) * 4         # PinId (repeated)
    data += fname(0, 0)        # PinName
    data += empty_ftext()      # PinFriendlyName
    data += i32(-1)            # SourceIndex (INDEX_NONE)
    data += empty_fstring()    # PinToolTip
    data += u8(0)              # Direction
    data += simple_pin_type()  # PinType
    data += empty_fstring()    # DefaultValue
    data += empty_fstring()    # AutogeneratedDefaultValue
    data += i32(0)             # DefaultObject (PackageIndex)
    data += empty_ftext()      # DefaultTextValue
    data += i32(0)             # LinkedTo count = 0
    data += i32(0)             # SubPins count = 0
    data += u32(1)             # ParentPin bNullPtr = true
    data += u32(1)             # RefPassThroughConnection bNullPtr = true
    # Editor-only tail
    data += u32(0) * 4         # PersistentGuid (FGuid)
    data += u32(0)             # BitField
    return data


def build_tail(guid_marker: int, pins: list[bytes]) -> bytes:
    """Build tail data: guid_marker + [optional 16-byte GUID] + pin_count + pin data."""
    data = b""
    data += u32(guid_marker)
    if guid_marker != 0:
        data += u32(0) * 4     # 16-byte GUID
    data += i32(len(pins))
    for pin in pins:
        data += pin
    return data


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

class TestGuidMarkerZero:
    """GUID marker = 0: no GUID bytes consumed."""

    def test_single_pin_decoded(self):
        """When guid_marker=0, single pin decodes correctly."""
        pin = build_single_pin()
        tail = build_tail(guid_marker=0, pins=[pin])

        archive = ByteArchive(tail, tolerant=True)
        name_map: list[str] = []
        mock_export = MockExport()

        result = _decode_pins_from_tail(archive, name_map, tail_offset=0, tail_size=len(tail), export=mock_export)

        assert len(result) == 1
        # Empty name_map + tolerant mode returns "None" for out-of-range index
        assert result[0]["pin_name"] in ("", "None")

    def test_multiple_pins_decoded(self):
        """When guid_marker=0, multiple pins decode correctly."""
        pin = build_single_pin()
        tail = build_tail(guid_marker=0, pins=[pin, pin, pin])

        archive = ByteArchive(tail, tolerant=True)
        name_map: list[str] = []
        mock_export = MockExport()

        result = _decode_pins_from_tail(archive, name_map, tail_offset=0, tail_size=len(tail), export=mock_export)

        assert len(result) == 3

    def test_zero_pins(self):
        """When guid_marker=0 and pin_count=0, returns empty list."""
        tail = build_tail(guid_marker=0, pins=[])

        archive = ByteArchive(tail, tolerant=True)
        name_map: list[str] = []

        result = _decode_pins_from_tail(archive, name_map, tail_offset=0, tail_size=len(tail))

        assert result == []


class TestGuidMarkerNonZero:
    """GUID marker != 0: 16-byte GUID must be consumed."""

    def test_single_pin_decoded_with_guid(self):
        """When guid_marker!=0, single pin decodes correctly after GUID consumption."""
        pin = build_single_pin()
        tail = build_tail(guid_marker=0xDEADBEEF, pins=[pin])

        archive = ByteArchive(tail, tolerant=True)
        name_map: list[str] = []
        mock_export = MockExport()

        result = _decode_pins_from_tail(archive, name_map, tail_offset=0, tail_size=len(tail), export=mock_export)

        assert len(result) == 1

    def test_multiple_pins_decoded_with_guid(self):
        """When guid_marker!=0, multiple pins decode correctly after GUID consumption."""
        pin = build_single_pin()
        tail = build_tail(guid_marker=1, pins=[pin, pin])

        archive = ByteArchive(tail, tolerant=True)
        name_map: list[str] = []
        mock_export = MockExport()

        result = _decode_pins_from_tail(archive, name_map, tail_offset=0, tail_size=len(tail), export=mock_export)

        assert len(result) == 2

    def test_pin_alignment_with_guid(self):
        """Pin data is correctly aligned after GUID consumption (pin_id is valid hex)."""
        pin = build_single_pin()
        tail = build_tail(guid_marker=0x12345678, pins=[pin])

        archive = ByteArchive(tail, tolerant=True)
        name_map: list[str] = []
        mock_export = MockExport()

        result = _decode_pins_from_tail(archive, name_map, tail_offset=0, tail_size=len(tail), export=mock_export)

        assert len(result) == 1
        pin_id = result[0]["pin_id"]
        # pin_id should be a valid hex GUID format
        parts = pin_id.split("-")
        assert len(parts) == 4
        for part in parts:
            assert len(part) == 8
            int(part, 16)  # should not raise

    def test_direction_decoded_correctly_with_guid(self):
        """Pin direction is correctly decoded after GUID consumption."""
        pin = build_single_pin()
        tail = build_tail(guid_marker=0xABCD, pins=[pin])

        archive = ByteArchive(tail, tolerant=True)
        name_map: list[str] = []
        mock_export = MockExport()

        result = _decode_pins_from_tail(archive, name_map, tail_offset=0, tail_size=len(tail), export=mock_export)

        assert len(result) == 1
        assert result[0]["direction"] == 0


class TestTailSizeEdgeCases:
    """Edge cases for tail size validation."""

    def test_tail_too_small_returns_empty(self):
        """Tail smaller than 8 bytes returns empty list."""
        tail = u32(0) + u8(0)  # Only 5 bytes (< 8 minimum)
        archive = ByteArchive(tail, tolerant=True)
        name_map: list[str] = []

        result = _decode_pins_from_tail(archive, name_map, tail_offset=0, tail_size=len(tail))

        assert result == []

    def test_tail_exactly_minimum_with_guid_marker(self):
        """Tail of exactly 8 bytes (guid_marker + pin_count) returns empty pins list."""
        tail = u32(0) + i32(0)  # guid_marker=0, pin_count=0
        archive = ByteArchive(tail, tolerant=True)
        name_map: list[str] = []

        result = _decode_pins_from_tail(archive, name_map, tail_offset=0, tail_size=len(tail))

        assert result == []


class TestExistingSampleRegression:
    """Regression: existing Niagara sample still parses."""

    @pytest.mark.samples
    def test_nm_bp_system_event_parses(self):
        """NM_BPSystemEvent.uasset parses without error."""
        sample_path = Path(__file__).resolve().parents[1] / "samples" / "NM_BPSystemEvent.uasset"
        if not sample_path.exists():
            pytest.skip("Sample not available")

        result = parse_uasset_with_linker(str(sample_path), tolerant=True)
        assert result.is_success, f"Parse failed: {result.errors}"
        assert result.linker is not None
        assert result.export_map is not None
