"""Runtime default value selection (BP-§12).

v1 implements rules 1, 2, 4-8. Rule 3 (bDefaultValueIsIgnored) is not parsed
by the serializer yet — treated as unavailable, never guessed. Rule 7:
AutogeneratedDefaultValue is debug evidence only.
"""
from __future__ import annotations

from typing import Any


def default_value_for(pin, reporting) -> Any:
    """Semantic runtime default for an input data pin, or None."""
    if getattr(pin, "linked_to", None):
        return None
    category = (getattr(pin, "pin_category", "") or "").lower()
    raw = getattr(pin, "default_value", "") or ""

    if category in ("object", "class", "interface", "softobject"):
        obj = getattr(pin, "default_object_name", None)
        if obj:
            return {"object": obj}
        if raw:
            return {"object": raw}
        return None

    if category == "text":
        text = getattr(pin, "default_text_value", None)
        return {"text": {"raw": text}} if text is not None else None

    if raw == "":
        if category in ("string", "name"):
            return ""
        return None

    if category == "bool":
        return raw.strip().lower() == "true"
    if category in ("int", "int8", "int64", "byte", "uint8", "uint16", "uint32", "uint64"):
        try:
            return int(raw)
        except ValueError:
            reporting.diagnostic("BP_DEFAULT_UNRESOLVED", "graphs", "info", "value_loss",
                                 occurrence={"value": raw[:64]})
            return {"raw": {"value": raw[:256], "expected": category}}
    if category in ("real", "float", "double"):
        try:
            return float(raw)
        except ValueError:
            reporting.diagnostic("BP_DEFAULT_UNRESOLVED", "graphs", "info", "value_loss",
                                 occurrence={"value": raw[:64]})
            return {"raw": {"value": raw[:256], "expected": category}}
    if category in ("string", "name"):
        return raw
    if category == "enum":
        return {"enum": raw}
    return _bounded_raw(raw, category or "unknown", reporting)


def _bounded_raw(raw: str, expected: str, reporting) -> dict:
    """BP-§15.5: bounding a large value must be visible, never silent."""
    value = {"value": raw[:256], "expected": expected}
    if len(raw) > 256:
        value["truncated"] = True
        value["original_length"] = len(raw)
        reporting.coverage("graphs", "truncated", reason="bounded_default_value",
                           declared=len(raw), emitted=256, omitted=len(raw) - 256)
        reporting.diagnostic("BP_DEFAULT_TRUNCATED", "graphs", "info", "value_loss")
    return {"raw": value}
