"""Runtime default value selection (BP-§12).

v1 implements rules 1, 2, 4-8. Rule 3 (bDefaultValueIsIgnored) is not parsed
by the serializer yet — treated as unavailable, never guessed. Rule 7:
AutogeneratedDefaultValue is debug evidence only.
"""
