"""兼容层 — 已废弃的公共导出映射。

通过 `uasset_read.__getattr__` 延迟加载并发出 DeprecationWarning。
新增代码应从子模块直接导入，不要使用这些废弃路径。
"""

DEPRECATED_IMPORTS: dict[str, tuple[str, str]] = {
    # --- 常量（基础） ---
    "PACKAGE_FILE_TAG": (".constants", "PACKAGE_FILE_TAG"),
    "PACKAGE_FILE_TAG_SWAPPED": (".constants", "PACKAGE_FILE_TAG_SWAPPED"),
    "UE5_VERSION_MIN": (".constants", "UE5_VERSION_MIN"),
    "UE5_LEGACY_VERSION": (".constants", "UE5_LEGACY_VERSION"),
    "MAX_NAME_COUNT": (".constants", "MAX_NAME_COUNT"),
    "MAX_IMPORT_COUNT": (".constants", "MAX_IMPORT_COUNT"),
    "MAX_EXPORT_COUNT": (".constants", "MAX_EXPORT_COUNT"),
    "MAX_CUSTOM_VERSIONS": (".constants", "MAX_CUSTOM_VERSIONS"),
    "MMAP_THRESHOLD": (".constants", "MMAP_THRESHOLD"),
    "MAX_PROPERTY_COUNT": (".constants", "MAX_PROPERTY_COUNT"),
    "PROPERTY_TAG_COMPLETE_TYPE_NAME": (".constants", "PROPERTY_TAG_COMPLETE_TYPE_NAME"),
    # 常量（图解析边界）
    "MAX_PINS_PER_NODE": (".constants", "MAX_PINS_PER_NODE"),
    "MAX_NODES_PER_GRAPH": (".constants", "MAX_NODES_PER_GRAPH"),
    "MAX_LINKEDTO_PER_PIN": (".constants", "MAX_LINKEDTO_PER_PIN"),
    # 常量（PropertyTag 标志）
    "PROP_TAG_NONE": (".constants", "PROP_TAG_NONE"),
    "PROP_TAG_HAS_ARRAY_INDEX": (".constants", "PROP_TAG_HAS_ARRAY_INDEX"),
    "PROP_TAG_HAS_PROPERTY_GUID": (".constants", "PROP_TAG_HAS_PROPERTY_GUID"),
    "PROP_TAG_HAS_EXTENSIONS": (".constants", "PROP_TAG_HAS_EXTENSIONS"),
    "PROP_TAG_HAS_BINARY_OR_NATIVE": (".constants", "PROP_TAG_HAS_BINARY_OR_NATIVE"),
    "PROP_TAG_BOOL_TRUE": (".constants", "PROP_TAG_BOOL_TRUE"),
    "PROP_TAG_SKIPPED_SERIALIZE": (".constants", "PROP_TAG_SKIPPED_SERIALIZE"),
    # 常量（控制流/事件类型集合）
    "CONTROL_FLOW_NODES": (".constants", "CONTROL_FLOW_NODES"),
    "START_EVENT_TYPES": (".constants", "START_EVENT_TYPES"),
    "BRANCH_TYPE_MAP": (".constants", "BRANCH_TYPE_MAP"),
    # 常量（Package Flags）
    "PKG_None": (".constants", "PKG_None"),
    "PKG_NewlyCreated": (".constants", "PKG_NewlyCreated"),
    "PKG_ClientOptional": (".constants", "PKG_ClientOptional"),
    "PKG_ServerSideOnly": (".constants", "PKG_ServerSideOnly"),
    "PKG_CompiledIn": (".constants", "PKG_CompiledIn"),
    "PKG_ForDiffing": (".constants", "PKG_ForDiffing"),
    "PKG_EditorOnly": (".constants", "PKG_EditorOnly"),
    "PKG_Developer": (".constants", "PKG_Developer"),
    "PKG_UncookedOnly": (".constants", "PKG_UncookedOnly"),
    "PKG_Cooked": (".constants", "PKG_Cooked"),
    "PKG_ContainsNoAsset": (".constants", "PKG_ContainsNoAsset"),
    "PKG_NotExternallyReferenceable": (".constants", "PKG_NotExternallyReferenceable"),
    "PKG_AccessSpecifierEpicInternal": (".constants", "PKG_AccessSpecifierEpicInternal"),
    "PKG_UnversionedProperties": (".constants", "PKG_UnversionedProperties"),
    "PKG_ContainsMapData": (".constants", "PKG_ContainsMapData"),
    "PKG_IsSaving": (".constants", "PKG_IsSaving"),
    "PKG_Compiling": (".constants", "PKG_Compiling"),
    "PKG_ContainsMap": (".constants", "PKG_ContainsMap"),
    "PKG_RequiresLocalizationGather": (".constants", "PKG_RequiresLocalizationGather"),
    "PKG_LoadUncooked": (".constants", "PKG_LoadUncooked"),
    "PKG_PlayInEditor": (".constants", "PKG_PlayInEditor"),
    "PKG_ContainsScript": (".constants", "PKG_ContainsScript"),
    "PKG_DisallowExport": (".constants", "PKG_DisallowExport"),
    "PKG_CookGenerated": (".constants", "PKG_CookGenerated"),
    "PKG_DynamicImports": (".constants", "PKG_DynamicImports"),
    "PKG_RuntimeGenerated": (".constants", "PKG_RuntimeGenerated"),
    "PKG_ReloadingForCooker": (".constants", "PKG_ReloadingForCooker"),
    "PKG_FilterEditorOnly": (".constants", "PKG_FilterEditorOnly"),
    "PKG_TransientFlags": (".constants", "PKG_TransientFlags"),
    "PKG_InMemoryOnly": (".constants", "PKG_InMemoryOnly"),
    "decode_package_flags": (".constants", "decode_package_flags"),
    # 常量（UE5 版本）
    "UE5_SCRIPT_SERIALIZATION_OFFSET": (".constants", "UE5_SCRIPT_SERIALIZATION_OFFSET"),
    "UE5_PROPERTY_TAG_EXTENSION": (".constants", "UE5_PROPERTY_TAG_EXTENSION"),
    "UE5_PROPERTY_TAG_COMPLETE_TYPE_NAME": (".constants", "UE5_PROPERTY_TAG_COMPLETE_TYPE_NAME"),
    "UE5_REMOVE_OBJECT_EXPORT_PACKAGE_GUID": (".constants", "UE5_REMOVE_OBJECT_EXPORT_PACKAGE_GUID"),
    "UE5_TRACK_OBJECT_EXPORT_IS_INHERITED": (".constants", "UE5_TRACK_OBJECT_EXPORT_IS_INHERITED"),
    "UE5_OPTIONAL_RESOURCES": (".constants", "UE5_OPTIONAL_RESOURCES"),
    "UE5_NAMES_REFERENCED_FROM_EXPORT_DATA": (".constants", "UE5_NAMES_REFERENCED_FROM_EXPORT_DATA"),
    "UE5_PAYLOAD_TOC": (".constants", "UE5_PAYLOAD_TOC"),
    "UE5_LARGE_WORLD_COORDINATES": (".constants", "UE5_LARGE_WORLD_COORDINATES"),
    "UE5_FSOFTOBJECTPATH_REMOVE_ASSET_PATH_FNAMES": (".constants", "UE5_FSOFTOBJECTPATH_REMOVE_ASSET_PATH_FNAMES"),
    "UE5_ADD_SOFTOBJECTPATH_LIST": (".constants", "UE5_ADD_SOFTOBJECTPATH_LIST"),
    "UE5_DATA_RESOURCES": (".constants", "UE5_DATA_RESOURCES"),
    "UE5_ASSETREGISTRY_PACKAGEBUILDDEPENDENCIES": (".constants", "UE5_ASSETREGISTRY_PACKAGEBUILDDEPENDENCIES"),
    "UE5_METADATA_SERIALIZATION_OFFSET": (".constants", "UE5_METADATA_SERIALIZATION_OFFSET"),
    "UE5_VERSE_CELLS": (".constants", "UE5_VERSE_CELLS"),
    "UE5_PACKAGE_SAVED_HASH": (".constants", "UE5_PACKAGE_SAVED_HASH"),
    "UE5_OS_SUB_OBJECT_SHADOW_SERIALIZATION": (".constants", "UE5_OS_SUB_OBJECT_SHADOW_SERIALIZATION"),
    "UE5_IMPORT_TYPE_HIERARCHIES": (".constants", "UE5_IMPORT_TYPE_HIERARCHIES"),
    # 常量（Framework/UE5MainStream/Release Version）
    "FFRAMEWORK_OBJECT_VERSION_GUID": (".constants", "FFRAMEWORK_OBJECT_VERSION_GUID"),
    "FFRAMEWORK_VERSION_ED_GRAPH_PIN_CONTAINER_TYPE": (".constants", "FFRAMEWORK_VERSION_ED_GRAPH_PIN_CONTAINER_TYPE"),
    "FFRAMEWORK_VERSION_PINS_STORE_FNAME": (".constants", "FFRAMEWORK_VERSION_PINS_STORE_FNAME"),
    "FUE5_MAINSTREAM_VERSION_GUID": (".constants", "FUE5_MAINSTREAM_VERSION_GUID"),
    "FUE5_MAINSTREAM_VERSION_ED_GRAPH_PIN_SOURCE_INDEX": (".constants", "FUE5_MAINSTREAM_VERSION_ED_GRAPH_PIN_SOURCE_INDEX"),
    "FRELEASE_OBJECT_VERSION_GUID": (".constants", "FRELEASE_OBJECT_VERSION_GUID"),
    "FRELEASE_VERSION_PIN_TYPE_UOBJECT_WRAPPER": (".constants", "FRELEASE_VERSION_PIN_TYPE_UOBJECT_WRAPPER"),
    # 常量（输出配置）
    "FORMAT_CONFIG": (".constants", "FORMAT_CONFIG"),
    # CPF 常量
    "CPF_Edit": (".constants", "CPF_Edit"),
    "CPF_BlueprintVisible": (".constants", "CPF_BlueprintVisible"),
    "CPF_InstancedReference": (".constants", "CPF_InstancedReference"),
    "CPF_BlueprintReadOnly": (".constants", "CPF_BlueprintReadOnly"),
    "CPF_Transient": (".constants", "CPF_Transient"),
    "CPF_SaveGame": (".constants", "CPF_SaveGame"),
    "CPF_ExposeOnSpawn": (".constants", "CPF_ExposeOnSpawn"),
    # --- 异常类 ---
    "UAssetError": (".exceptions", "UAssetError"),
    "VersionError": (".exceptions", "VersionError"),
    "DecompressionError": (".exceptions", "DecompressionError"),
    "LinkerError": (".exceptions", "LinkerError"),
    "ErrorContext": (".exceptions", "ErrorContext"),
    # --- 序列化模块 ---
    "PackageFileSummary": (".serializers", "PackageFileSummary"),
    "PackageIndex": (".serializers", "PackageIndex"),
    "ObjectImport": (".serializers", "ObjectImport"),
    "ObjectExport": (".serializers", "ObjectExport"),
    "EngineVersion": (".serializers", "EngineVersion"),
    "CustomVersion": (".serializers", "CustomVersion"),
    "GenerationInfo": (".serializers", "GenerationInfo"),
    "read_package_summary": (".serializers", "read_package_summary"),
    "read_name_table": (".serializers", "read_name_table"),
    "read_import_map": (".serializers", "read_import_map"),
    "read_export_map": (".serializers", "read_export_map"),
    "detect_blueprint": (".serializers", "detect_blueprint"),
    "build_imports_list": (".serializers", "build_imports_list"),
    "get_asset_class": (".serializers", "get_asset_class"),
    "resolve_class_name": (".serializers", "resolve_class_name"),
    "detect_blueprint_generated_class": (".serializers", "detect_blueprint_generated_class"),
    "validate_package_index": (".serializers", "validate_package_index"),
    # 图序列化
    "read_ue_graph": (".serializers", "read_ue_graph"),
    "read_ue_graph_node": (".serializers", "read_ue_graph_node"),
    "read_ue_graph_pin": (".serializers", "read_ue_graph_pin"),
    "read_ed_graph_pin_type": (".serializers", "read_ed_graph_pin_type"),
    "read_fmember_reference": (".serializers", "read_fmember_reference"),
    "create_node_from_archive": (".serializers", "create_node_from_archive"),
    # 节点类型读取器
    "read_k2node_call_function": (".serializers", "read_k2node_call_function"),
    "read_k2node_event": (".serializers", "read_k2node_event"),
    "read_k2node_knot": (".serializers", "read_k2node_knot"),
    "read_edgraph_node_comment": (".serializers", "read_edgraph_node_comment"),
    "read_k2node_enhanced_input": (".serializers", "read_k2node_enhanced_input"),
    "read_k2node_functionentry": (".serializers", "read_k2node_functionentry"),
    # --- 核心数据模型 ---
    "FEdGraphPinType": (".models", "FEdGraphPinType"),
    "UEdGraphPin": (".models", "UEdGraphPin"),
    "UEdGraphNode": (".models", "UEdGraphNode"),
    "UEdGraph": (".models", "UEdGraph"),
    "FMemberReference": (".models", "FMemberReference"),
    # 节点类型
    "K2NodeCallFunction": (".models", "K2NodeCallFunction"),
    "K2NodeEvent": (".models", "K2NodeEvent"),
    "K2NodeKnot": (".models", "K2NodeKnot"),
    "EdGraphNodeComment": (".models", "EdGraphNodeComment"),
    "K2NodeEnhancedInputAction": (".models", "K2NodeEnhancedInputAction"),
    "K2NodeFunctionEntry": (".models", "K2NodeFunctionEntry"),
    # 结果
    "StatusInfo": (".models", "StatusInfo"),
    # 蓝图元数据
    "BlueprintMetadata": (".models", "BlueprintMetadata"),
    "BlueprintVariable": (".models", "BlueprintVariable"),
    "BlueprintFunction": (".models", "BlueprintFunction"),
    "BlueprintEvent": (".models", "BlueprintEvent"),
    "FunctionParameter": (".models", "FunctionParameter"),
    "MulticastDelegate": (".models", "MulticastDelegate"),
    # --- 映射模型 ---
    "TypeMappingsProvider": (".mappings", "TypeMappingsProvider"),
    "UsmapParser": (".mappings", "UsmapParser"),
    "JmapParser": (".mappings", "JmapParser"),
    "TypeMappings": (".mappings", "TypeMappings"),
    "StructMapping": (".mappings", "StructMapping"),
    "PropertyType": (".mappings", "PropertyType"),
    "PropertyInfo": (".mappings", "PropertyInfo"),
    # --- 属性数据模型 ---
    "PropertyTag": (".models", "PropertyTag"),
    "PropertyTypeName": (".models", "PropertyTypeName"),
    "PropertyValue": (".models", "PropertyValue"),
    "SoftObjectPathValue": (".models", "SoftObjectPathValue"),
    "AdvancedPropertyValue": (".models", "AdvancedPropertyValue"),
    "StructValue": (".models", "StructValue"),
    "MapValue": (".models", "MapValue"),
    "SetValue": (".models", "SetValue"),
    "EnumValue": (".models", "EnumValue"),
    "TextValue": (".models", "TextValue"),
    "DelegateValue": (".models", "DelegateValue"),
    # --- Fallback 模型 ---
    "PropertyFallback": (".models", "PropertyFallback"),
    "StructFallback": (".models", "StructFallback"),
    "GenericUObject": (".models", "GenericUObject"),
    "ExportParseStatus": (".models", "ExportParseStatus"),
    "FallbackReason": (".models", "FallbackReason"),
    "OffsetRangeDiagnostic": (".models", "OffsetRangeDiagnostic"),
    # --- 变换数据类 ---
    "VectorValue": (".models.transforms", "VectorValue"),
    "RotatorValue": (".models.transforms", "RotatorValue"),
    "ScaleValue": (".models.transforms", "ScaleValue"),
    "format_transform_value": (".models.transforms", "format_transform_value"),
    # --- Class Handler Registry ---
    "ClassHandlerRegistry": (".parsers.class_registry", "ClassHandlerRegistry"),
    "ClassHandler": (".parsers.class_registry", "ClassHandler"),
    "HandlerResult": (".parsers.class_registry", "HandlerResult"),
    "FallbackPolicy": (".parsers.class_registry", "FallbackPolicy"),
    "get_class_registry": (".parsers.class_registry", "get_class_registry"),
    # --- 解析器模块 ---
    "parse_property_value": (".parsers", "parse_property_value"),
    "parse_properties_from_export": (".parsers", "parse_properties_from_export"),
    "parse_bool_property": (".parsers", "parse_bool_property"),
    "parse_int_property": (".parsers", "parse_int_property"),
    "parse_float_property": (".parsers", "parse_float_property"),
    "parse_str_property": (".parsers", "parse_str_property"),
    "parse_name_property": (".parsers", "parse_name_property"),
    "parse_object_property": (".parsers", "parse_object_property"),
    "parse_soft_object_property": (".parsers", "parse_soft_object_property"),
    "parse_array_property": (".parsers", "parse_array_property"),
    "parse_struct_property": (".parsers", "parse_struct_property"),
    "parse_map_property": (".parsers", "parse_map_property"),
    "parse_set_property": (".parsers", "parse_set_property"),
    "parse_enum_property": (".parsers", "parse_enum_property"),
    "parse_text_property": (".parsers", "parse_text_property"),
    "parse_delegate_property": (".parsers", "parse_delegate_property"),
    "parse_uint16_property": (".parsers", "parse_uint16_property"),
    "parse_uint32_property": (".parsers", "parse_uint32_property"),
    "parse_uint64_property": (".parsers", "parse_uint64_property"),
    "parse_utf8_str_property": (".parsers", "parse_utf8_str_property"),
    "parse_weak_object_property": (".parsers", "parse_weak_object_property"),
    "parse_lazy_object_property": (".parsers", "parse_lazy_object_property"),
    "parse_class_property": (".parsers", "parse_class_property"),
    "parse_soft_class_property": (".parsers", "parse_soft_class_property"),
    "parse_asset_object_property": (".parsers", "parse_asset_object_property"),
    "parse_multicast_delegate_property": (".parsers", "parse_multicast_delegate_property"),
    "parse_multicast_inline_delegate_property": (".parsers", "parse_multicast_inline_delegate_property"),
    "parse_multicast_sparse_delegate_property": (".parsers", "parse_multicast_sparse_delegate_property"),
    "parse_interface_property": (".parsers", "parse_interface_property"),
    "parse_field_path_property": (".parsers", "parse_field_path_property"),
    "parse_optional_property": (".parsers", "parse_optional_property"),
    "parse_verse_string_property": (".parsers", "parse_verse_string_property"),
    "parse_verse_class_property": (".parsers", "parse_verse_class_property"),
    "parse_verse_function_property": (".parsers", "parse_verse_function_property"),
    "parse_verse_dynamic_property": (".parsers", "parse_verse_dynamic_property"),
    "parse_verse_cell_property": (".parsers", "parse_verse_cell_property"),
    "parse_verse_value_property": (".parsers", "parse_verse_value_property"),
    "parse_ansi_str_property": (".parsers", "parse_ansi_str_property"),
    "parse_double_property": (".parsers", "parse_double_property"),
    "parse_guid_property": (".parsers", "parse_guid_property"),
    # CustomProperty 注册表
    "CUSTOM_PROPERTY_HANDLERS": (".parsers", "CUSTOM_PROPERTY_HANDLERS"),
    "CustomPropertyContext": (".parsers", "CustomPropertyContext"),
    "register_custom_property": (".parsers", "register_custom_property"),
    "handle_custom_property": (".parsers", "handle_custom_property"),
    # 辅助函数
    "get_struct_size": (".parsers", "get_struct_size"),
    "resolve_name_from_index": (".parsers", "resolve_name_from_index"),
    "read_validated_count_tolerant": (".parsers", "read_validated_count_tolerant"),
    "make_enum_value": (".parsers", "make_enum_value"),
    "extract_inner_from_tag": (".parsers", "extract_inner_from_tag"),
    # --- 蓝图模块 ---
    "extract_blueprint_variables": (".blueprint", "extract_blueprint_variables"),
    "parse_component_transform": (".blueprint", "parse_component_transform"),
    "extract_blueprint_metadata": (".blueprint", "extract_blueprint_metadata"),
    "extract_components": (".blueprint", "extract_components"),
    "extract_component_transforms": (".blueprint.transform_parser", "extract_component_transforms"),
    "parse_vector_value": (".blueprint.transform_parser", "parse_vector_value"),
    "parse_rotator_value": (".blueprint.transform_parser", "parse_rotator_value"),
    "parse_scale_value": (".blueprint.transform_parser", "parse_scale_value"),
    "read_blueprint_variable": (".blueprint.variable_extractor", "read_blueprint_variable"),
    "parse_property_flags_to_labels": (".blueprint.variable_extractor", "parse_property_flags_to_labels"),
    # --- 图解析模块 ---
    "extract_blueprint_graphs": (".graph", "extract_blueprint_graphs"),
    "build_execution_flow_entries": (".graph", "build_execution_flow_entries"),
    "build_data_flows": (".graph", "build_data_flows"),
    "build_connections_map": (".graph", "build_connections_map"),
    "format_graphs_json": (".graph", "format_graphs_json"),
    "build_execution_chains": (".graph", "build_execution_chains"),
    "format_pin_ref": (".graph", "format_pin_ref"),
    "build_function_graphs": (".graph", "build_function_graphs"),
    # --- 内存安全 ---
    "MemoryLimitExceeded": (".memory_safety", "MemoryLimitExceeded"),
    "MemoryPolicy": (".memory_safety", "MemoryPolicy"),
    "ResourceLimits": (".memory_safety", "ResourceLimits"),
    # --- 主解析管线辅助 ---
    "PackageBundle": (".package", "PackageBundle"),
    "PackageProvider": (".package", "PackageProvider"),
    "FileSystemPackageProvider": (".package", "FileSystemPackageProvider"),
    "PakPackageProvider": (".package", "PakPackageProvider"),
    "IoStorePackageProvider": (".package", "IoStorePackageProvider"),
    "open_package_bundle": (".package", "open_package_bundle"),
    # --- Raw 文件解析 ---
    "RawFileResult": (".raw", "RawFileResult"),
    "parse_raw_file": (".raw", "parse_raw_file"),
    "parse_json_descriptor": (".raw", "parse_json_descriptor"),
    "parse_ini_file": (".raw", "parse_ini_file"),
    "parse_locres": (".raw", "parse_locres"),
    "parse_locmeta": (".raw", "parse_locmeta"),
    "parse_audio_metadata": (".raw", "parse_audio_metadata"),
    # --- Object Resources 辅助 ---
    "find_main_blueprint_generated_class": (".serializers.object_resources", "find_main_blueprint_generated_class"),
    "resolve_parent_class": (".serializers.object_resources", "resolve_parent_class"),
    "resolve_class_name_with_linker": (".serializers.object_resources", "resolve_class_name_with_linker"),
    "get_asset_class_with_linker": (".serializers.object_resources", "get_asset_class_with_linker"),
    "detect_blueprint_with_linker": (".serializers.object_resources", "detect_blueprint_with_linker"),
    "resolve_parent_class_with_linker": (".serializers.object_resources", "resolve_parent_class_with_linker"),
    "read_soft_object_paths": (".serializers.object_resources", "read_soft_object_paths"),
    # --- Property Tags ---
    "read_property_tag": (".serializers.property_tags", "read_property_tag"),
    "parse_ctrl_flags": (".serializers.property_tags", "parse_ctrl_flags"),
    # --- Property Types ---
    "parse_default_value": (".parsers.property_types", "parse_default_value"),
    "format_variable_type": (".parsers.property_types", "format_variable_type"),
    # --- Kismet 字节码 ---
    "EExprToken": (".kismet", "EExprToken"),
    "ECastToken": (".kismet", "ECastToken"),
    "EScriptInstrumentationType": (".kismet", "EScriptInstrumentationType"),
    "EBlueprintTextLiteralType": (".kismet", "EBlueprintTextLiteralType"),
    "EAutoRtfmStopTransactMode": (".kismet", "EAutoRtfmStopTransactMode"),
    "KismetExpression": (".kismet", "KismetExpression"),
    "KismetExpressionT": (".kismet", "KismetExpressionT"),
    "EXPR_CLASS_MAP": (".kismet", "EXPR_CLASS_MAP"),
    "FKismetPropertyPointer": (".kismet", "FKismetPropertyPointer"),
    "FFieldPath": (".kismet", "FFieldPath"),
    "FKismetArchive": (".kismet", "FKismetArchive"),
    "USTRUCT_TYPES": (".kismet", "USTRUCT_TYPES"),
    "reset_bpgc_cache": (".kismet", "reset_bpgc_cache"),
    # Kismet C++ translator
    "KismetTranslator": (".kismet", "KismetTranslator"),
    "MathFunctionCleaner": (".kismet", "MathFunctionCleaner"),
    "TypeRegistry": (".kismet", "TypeRegistry"),
    "line_cpp": (".kismet", "line_cpp"),
    "UE_TYPE_MAP": (".kismet", "UE_TYPE_MAP"),
    "FunctionBodyBuilder": (".kismet", "FunctionBodyBuilder"),
    "to_function_body": (".kismet", "to_function_body"),
    "StructuredControlFlow": (".kismet", "StructuredControlFlow"),
    "StructuredBlock": (".kismet", "StructuredBlock"),
    # Kismet 字节码提取
    "extract_bytecode_bytes": (".kismet", "extract_bytecode_bytes"),
    "parse_bytecode_stream": (".kismet", "parse_bytecode_stream"),
    "extract_and_parse": (".kismet", "extract_and_parse"),
    # Kismet 反编译管线
    "KismetDecompiledResult": (".kismet.result", "KismetDecompiledResult"),
    "decompile_uasset": (".kismet.pipeline", "decompile_uasset"),
    "decompile_single_function": (".kismet.pipeline", "decompile_single_function"),
    # --- C++ 代码生成 ---
    "CppProperty": (".cpp_gen", "CppProperty"),
    "CppHeaderMeta": (".cpp_gen", "CppHeaderMeta"),
    "CppClassIR": (".cpp_gen", "CppClassIR"),
    "format_cpp_class_json": (".cpp_gen", "format_cpp_class_json"),
    "format_cpp_header": (".cpp_gen", "format_cpp_header"),
    "UE_TO_CPP_TYPE_MAP": (".cpp_gen", "UE_TO_CPP_TYPE_MAP"),
    "ENGINE_CLASS_PATHS": (".cpp_gen", "ENGINE_CLASS_PATHS"),
    "ue_path_to_cpp_type": (".cpp_gen", "ue_path_to_cpp_type"),
    "ue_package_path_to_cpp_class": (".cpp_gen", "ue_package_path_to_cpp_class"),
    "infer_class_prefix": (".cpp_gen", "infer_class_prefix"),
    "resolve_ue_type": (".cpp_gen", "resolve_ue_type"),
    "CPF_TO_UPROPERTY_MAP": (".cpp_gen", "CPF_TO_UPROPERTY_MAP"),
    "cpf_flags_to_uproperty_marks": (".cpp_gen", "cpf_flags_to_uproperty_marks"),
    "extract_cpp_class_skeleton": (".cpp_gen", "extract_cpp_class_skeleton"),
    "extract_cpp_constructor": (".cpp_gen", "extract_cpp_constructor"),
    "format_cpp_call_statements": (".cpp_gen", "format_cpp_call_statements"),
    "CppCallParameter": (".cpp_gen", "CppCallParameter"),
    "CppMethodIR": (".cpp_gen", "CppMethodIR"),
    "CppCallStatement": (".cpp_gen", "CppCallStatement"),
    "CppStatement": (".cpp_gen", "CppStatement"),
    "CppCallStmt": (".cpp_gen", "CppCallStmt"),
    "CppAssignmentStmt": (".cpp_gen", "CppAssignmentStmt"),
    "CppIfStmt": (".cpp_gen", "CppIfStmt"),
    "CppInlineExprStmt": (".cpp_gen", "CppInlineExprStmt"),
    "CppReturnStmt": (".cpp_gen", "CppReturnStmt"),
    "CppWhileStmt": (".cpp_gen", "CppWhileStmt"),
    "CppRawStmt": (".cpp_gen", "CppRawStmt"),
    "kismet_to_cpp_body": (".cpp_gen", "kismet_to_cpp_body"),
    "format_cpp_default_value": (".cpp_gen", "format_cpp_default_value"),
    "format_cpp_transform": (".cpp_gen", "format_cpp_transform"),
    "format_cpp_component_init": (".cpp_gen", "format_cpp_component_init"),
    "format_cpp_input_action_load": (".cpp_gen", "format_cpp_input_action_load"),
    "build_constructor_sections": (".cpp_gen", "build_constructor_sections"),
    "format_cpp_constructor": (".cpp_gen", "format_cpp_constructor"),
    "sanitize_identifier": (".cpp_gen", "sanitize_identifier"),
    # --- 版本管理 ---
    "VersionContainer": (".versioning", "VersionContainer"),
    "build_version_container": (".versioning", "build_version_container"),
    "EUEVersion": (".versioning", "EUEVersion"),
    # --- Link 模块 ---
    "PackageLinker": (".link", "PackageLinker"),
    "UObjectInstance": (".link", "UObjectInstance"),
    "LinkerParseResult": (".link", "LinkerParseResult"),
    # --- Pak 模块 ---
    "PAK_FILE_MAGIC": (".pak", "PAK_FILE_MAGIC"),
    "PakFileVersion": (".pak", "PakFileVersion"),
    "ECompressionFlags": (".pak", "ECompressionFlags"),
    "Flag_Encrypted": (".pak", "Flag_Encrypted"),
    "Flag_Deleted": (".pak", "Flag_Deleted"),
    "MaxNumCompressionMethods": (".pak", "MaxNumCompressionMethods"),
    "PAK_INFO_SIZES": (".pak", "PAK_INFO_SIZES"),
    "FPakCompressedBlock": (".pak", "FPakCompressedBlock"),
    "FPakEntry": (".pak", "FPakEntry"),
    "FPakInfo": (".pak", "FPakInfo"),
    "FPakDirectoryEntry": (".pak", "FPakDirectoryEntry"),
    "read_fstring": (".pak", "read_fstring"),
    "decompress_block": (".pak", "decompress_block"),
    "decompress_entry": (".pak", "decompress_entry"),
    "PakFileReader": (".pak", "PakFileReader"),
    # --- IoStore 容器系统 ---
    "IoStoreReader": (".iostore", "IoStoreReader"),
    "FIoChunkId": (".iostore", "FIoChunkId"),
    "FIoOffsetAndSize": (".iostore", "FIoOffsetAndSize"),
    # --- Bulk Data ---
    "FBulkDataHeader": (".bulk", "FBulkDataHeader"),
    "BulkDataFlags": (".bulk", "BulkDataFlags"),
}
