from __future__ import annotations

"""
BPGC Bytecode Extraction — BlueprintGeneratedClass cooked bytecode parsing.

Extract bytecode from BPGC script_serial_region (fallback
for UE5 cooked Blueprints where Function exports contain no bytecode).

Provides:
- extract_bpgc_bytecode: Read BPGC script region, parse cooked format into per-function buffers
- map_bytecode_to_functions: Map bytecode buffers to Function exports by ordinal position
- _parse_cooked_bytecode_buffer: Pure logic function for buffer splitting
"""

import logging
import struct
from dataclasses import dataclass, field
from enum import Enum
from typing import TYPE_CHECKING

from uasset_read.exceptions import ParseError
from uasset_read.constants import UE_NONE_SENTINEL

if TYPE_CHECKING:
    from uasset_read.archive import FArchive
    from uasset_read.serializers.object_resources import ObjectExport
    from uasset_read.serializers.package_summary import PackageFileSummary


logger = logging.getLogger(__name__)

# Cooked bytecode end-of-function sentinel variants
_END_OF_SCRIPT = 0x53        # EX_EndOfScript — standard
_COOKED_END_SENTINEL = 0xDD  # Cooked format variant seen in some UE5 assets


# ===========================================================================
# BPGC Extraction Diagnostic Metrics (#426)
# ===========================================================================


class BytecodeConfidenceLevel(Enum):
    """Bytecode recovery confidence level."""
    HIGH = "high"           # All buffer counts match, sentinels correct, no truncation
    MEDIUM = "medium"       # Sentinel mismatch or count inconsistency, but most data usable
    LOW = "low"             # Truncation or large number of empty buffers
    UNRECOVERABLE = "unrecoverable"  # No usable data


@dataclass
class BPGCExtractionMetrics:
    """BPGC bytecode extraction diagnostic metrics — records quality information about the extraction process.

    Used to assess extraction result confidence, aiding debugging and diagnostics.
    Generated by _parse_cooked_bytecode_buffer, passed through by extract_bpgc_bytecode.
    """
    # Raw data information
    total_raw_bytes: int = 0             # Total available bytes in script region
    class_script_skipped: bool = False   # Whether BPGC class's own script was skipped
    class_script_size: int = 0           # Size of skipped class script

    # Function declaration and extraction
    declared_function_count: int = 0     # Number of functions declared in header
    extracted_buffer_count: int = 0      # Number of buffers actually extracted

    # Buffer quality
    empty_buffer_count: int = 0          # Number of empty buffers (sz <= 0)
    sentinel_mismatch_count: int = 0     # Number of buffers not ending with expected sentinel
    truncated_buffer_count: int = 0      # Number of buffers truncated due to insufficient data

    # Mapping quality (populated by map_bytecode_to_functions)
    mapped_function_count: int = 0       # Number of buffers successfully mapped to functions
    mapping_mismatch: bool = False       # Whether buffer count mismatches function export count

    # Extraction-stage errors
    early_exit: bool = False             # Whether exited early due to data anomalies
    exit_reason: str = ""                # Reason for early exit

    def to_dict(self) -> dict:
        """Convert to JSON-compatible dict. Zero-value fields omitted to reduce output noise."""
        d: dict = {}
        if self.total_raw_bytes:
            d["total_raw_bytes"] = self.total_raw_bytes
        if self.class_script_skipped:
            d["class_script_skipped"] = True
            d["class_script_size"] = self.class_script_size
        if self.declared_function_count:
            d["declared_function_count"] = self.declared_function_count
        if self.extracted_buffer_count:
            d["extracted_buffer_count"] = self.extracted_buffer_count
        if self.empty_buffer_count:
            d["empty_buffer_count"] = self.empty_buffer_count
        if self.sentinel_mismatch_count:
            d["sentinel_mismatch_count"] = self.sentinel_mismatch_count
        if self.truncated_buffer_count:
            d["truncated_buffer_count"] = self.truncated_buffer_count
        if self.mapped_function_count:
            d["mapped_function_count"] = self.mapped_function_count
        if self.mapping_mismatch:
            d["mapping_mismatch"] = True
        if self.early_exit:
            d["early_exit"] = True
            d["exit_reason"] = self.exit_reason
        return d

    @property
    def confidence(self) -> BytecodeConfidenceLevel:
        """Compute confidence level based on metrics data."""
        # No extractable data
        if self.extracted_buffer_count == 0:
            return BytecodeConfidenceLevel.UNRECOVERABLE

        # Truncation present → low confidence
        if self.truncated_buffer_count > 0:
            return BytecodeConfidenceLevel.LOW

        # Large number of empty buffers (>50%) → low confidence
        if (self.empty_buffer_count > 0
                and self.empty_buffer_count > self.extracted_buffer_count // 2):
            return BytecodeConfidenceLevel.LOW

        # Early exit → low confidence
        if self.early_exit:
            return BytecodeConfidenceLevel.LOW

        # Sentinel mismatch or count inconsistency → medium confidence
        if self.sentinel_mismatch_count > 0 or self.mapping_mismatch:
            return BytecodeConfidenceLevel.MEDIUM

        # All normal → high confidence
        return BytecodeConfidenceLevel.HIGH


def _parse_cooked_bytecode_buffer(data: bytes) -> tuple[list[bytes], BPGCExtractionMetrics]:
    """Parse BPGC script region bytes into per-function bytecode buffers.

    BPGC cooked format (per UStruct/FStructScriptLoader + empirical verification):
    1. [i32 BytecodeBufferSize] — BPGC class's own script size
    2. [i32 SerializedScriptSize] — BPGC class script serialization size
    3. [i32 num_functions] — Number of function bytecode entries
    4. [num_functions × i32 bytecode_size] — Size of each function's bytecode
    5. [concatenated bytecode data] — Concatenated bytecode

    When SerializedScriptSize > 0, skip the corresponding bytes of class script data.

    Pure logic function — no archive or I/O dependency.

    Args:
        data: Raw script_serial_region content (after PropertyTags + optional headers)

    Returns:
        Tuple of (buffers, metrics):
        - buffers: List of bytecode buffers, one per function
        - metrics: BPGCExtractionMetrics diagnostic data

    Stops on:
        - data too short for header
        - num_functions > 10000 (unreasonable)
        - size exceeding remaining bytes
    """
    buffers: list[bytes] = []
    metrics = BPGCExtractionMetrics(total_raw_bytes=len(data))
    data_len = len(data)
    offset = 0

    # Step 1: Read BPGC class's own script header (BytecodeBufferSize + SerializedScriptSize)
    if data_len < 8:
        logger.debug("BPGC bytecode: data too short for header (%d bytes)", data_len)
        metrics.early_exit = True
        metrics.exit_reason = "data_too_short_for_header"
        return buffers, metrics

    _bb_size = struct.unpack_from('<i', data, offset)[0]
    ss_size = struct.unpack_from('<i', data, offset + 4)[0]
    offset += 8

    # Skip class script data if present (SerializedScriptSize > 0)
    if ss_size > 0:
        if offset + ss_size > data_len:
            logger.debug(
                "BPGC bytecode: class script SerializedScriptSize=%d exceeds data (%d bytes)",
                ss_size, data_len - offset,
            )
            metrics.early_exit = True
            metrics.exit_reason = "class_script_exceeds_data"
            return buffers, metrics
        metrics.class_script_skipped = True
        metrics.class_script_size = ss_size
        offset += ss_size

    # Step 2: Read function count
    if offset + 4 > data_len:
        logger.debug("BPGC bytecode: no room for function count at offset %d", offset)
        metrics.early_exit = True
        metrics.exit_reason = "no_room_for_function_count"
        return buffers, metrics

    num_functions = struct.unpack_from('<I', data, offset)[0]
    offset += 4
    metrics.declared_function_count = num_functions

    if num_functions == 0:
        logger.debug("BPGC bytecode: 0 functions declared")
        metrics.early_exit = True
        metrics.exit_reason = "zero_functions_declared"
        return buffers, metrics

    if num_functions > 10000:
        logger.debug(
            "BPGC bytecode: unreasonable function count %d at offset %d",
            num_functions, offset - 4,
        )
        metrics.early_exit = True
        metrics.exit_reason = f"unreasonable_function_count_{num_functions}"
        return buffers, metrics

    # Step 3: Read function bytecode sizes
    sizes_end = offset + num_functions * 4
    if sizes_end > data_len:
        logger.debug(
            "BPGC bytecode: not enough data for %d function sizes (need %d, have %d)",
            num_functions, sizes_end - offset, data_len - offset,
        )
        metrics.early_exit = True
        metrics.exit_reason = "not_enough_data_for_sizes"
        return buffers, metrics

    sizes: list[int] = []
    for i in range(num_functions):
        sz = struct.unpack_from('<i', data, offset)[0]
        sizes.append(sz)
        offset += 4

    # Step 4: Extract function bytecodes from concatenated data
    for i, sz in enumerate(sizes):
        if sz <= 0:
            buffers.append(b'')
            metrics.empty_buffer_count += 1
            continue

        if offset + sz > data_len:
            logger.debug(
                "BPGC bytecode buffer #%d: size=%d exceeds remaining %d bytes",
                i, sz, data_len - offset,
            )
            # Try to read remaining data
            sz = data_len - offset
            if sz <= 0:
                metrics.truncated_buffer_count += 1
                break
            metrics.truncated_buffer_count += 1

        buf = data[offset:offset + sz]
        offset += sz

        # Validate buffer ends with expected sentinel (tolerant)
        if buf and buf[-1] not in (_END_OF_SCRIPT, _COOKED_END_SENTINEL):
            logger.debug(
                "Bytecode buffer #%d ends with 0x%02X, accepting in tolerant mode",
                i, buf[-1],
            )
            metrics.sentinel_mismatch_count += 1

        buffers.append(buf)

    metrics.extracted_buffer_count = len(buffers)
    return buffers, metrics


def extract_bpgc_bytecode(
    archive: FArchive,
    bpgc_export: ObjectExport,
    summary: PackageFileSummary,
    asset_name: str,
    name_map: list[str],
    import_map: list,
    export_map: list,
) -> tuple[dict[str, bytes], BPGCExtractionMetrics]:
    """
    Extract cooked bytecode buffers from a BlueprintGeneratedClass export.

    Reads the BPGC's script_serial_region, skips PropertyTags until "None",
    then parses the cooked bytecode format (u32 size prefix per function buffer)
    into individual bytecode buffers.

    Args:
        archive: FArchive instance (file-level archive)
        bpgc_export: ObjectExport for the BlueprintGeneratedClass
        summary: PackageFileSummary for version flags
        asset_name: Asset name for logging/context
        name_map: Name table for PropertyTag parsing
        import_map: Import table for class resolution
        export_map: Export table for class resolution

    Returns:
        Tuple of (buffers_dict, metrics):
        - buffers_dict: Dict mapping function index (as string "0", "1", ...) to bytecode bytes.
          Empty dict if not a BPGC or no bytecode data.
        - metrics: BPGCExtractionMetrics diagnostic data

    Raises:
        ParseError: If script region structure is invalid
    """
    from uasset_read.serializers.object_resources import detect_blueprint_generated_class
    from uasset_read.serializers.property_tags import read_property_tag
    from uasset_read.constants import UE5_PROPERTY_TAG_EXTENSION

    empty_metrics = BPGCExtractionMetrics()

    # Step 1: Validate BPGC export
    if not detect_blueprint_generated_class(bpgc_export, import_map, export_map):
        logger.debug("Export '%s' is not a BlueprintGeneratedClass, skipping", bpgc_export.object_name)
        return {}, empty_metrics

    # Step 2: Check script_serialization
    if not bpgc_export.has_script_serialization:
        logger.debug("BPGC '%s' has no script_serial_region data", bpgc_export.object_name)
        return {}, empty_metrics

    # Step 3: Calculate script start position
    if summary.file_version_ue5 >= UE5_PROPERTY_TAG_EXTENSION:
        script_start = bpgc_export.serial_offset + bpgc_export.script_serialization_start_offset
    else:
        script_start = bpgc_export.serial_offset

    archive.seek(script_start)

    # Step 3b: SerializationControlExtensions header (same as extract_bytecode_bytes)
    if summary.file_version_ue5 >= UE5_PROPERTY_TAG_EXTENSION:
        ctrl = archive.read_u8()
        if ctrl & 0x02:
            archive.read_u8()  # skip overridden operation

    # Step 5: Skip PropertyTags until "None" terminator
    tag_count = 0
    while True:
        tag = read_property_tag(archive, name_map)
        if tag.name == UE_NONE_SENTINEL:
            break
        # Skip property value data using FArchive read_bytes
        archive.read_bytes(tag.size)
        tag_count += 1
        if tag_count > 10000:
            raise ParseError(
                f"Too many PropertyTags (>10000) in BPGC '{bpgc_export.object_name}' script region"
            )

    # Step 6: Read remaining script region bytes and parse cooked format
    region_end = bpgc_export.serial_offset + bpgc_export.serial_size
    current_pos = archive.tell()
    remaining_bytes = region_end - current_pos

    if remaining_bytes <= 0:
        logger.debug("BPGC '%s': no bytecode data after PropertyTags", bpgc_export.object_name)
        return {}, empty_metrics

    # Note: script_serialization_size only covers the PropertyTags region, not bytecode data.
    # Bytecode data is in the remaining part of the serial region (after PropertyTags).

    raw_bytecode = archive.read_bytes(remaining_bytes)

    # Step 7: Parse cooked bytecode buffers
    buffers, metrics = _parse_cooked_bytecode_buffer(raw_bytecode)

    if not buffers:
        # #343: Distinguish "no bytecode" from "parsing failure"
        # Note: remaining_bytes <= 0 case already handled above
        logger.debug(
            "BPGC '%s': _parse_cooked_bytecode_buffer returned empty (%d bytes available), "
            "possibly a format variant or data corruption",
            asset_name, remaining_bytes,
        )
        return {}, metrics

    logger.info(
        "BPGC '%s': extracted %d bytecode buffers from script_serial_region (confidence=%s)",
        bpgc_export.object_name, len(buffers), metrics.confidence.value,
    )

    # Return dict mapping index string to bytecode bytes
    return {str(i): buf for i, buf in enumerate(buffers)}, metrics


def map_bytecode_to_functions(
    bytecode_buffers: dict[str, bytes],
    function_exports: list[ObjectExport],
    name_map: list[str],
    import_map: list,
    export_map: list,
    metrics: BPGCExtractionMetrics | None = None,
) -> dict[str, bytes]:
    """
    Map bytecode buffers to Function exports by ordinal position.

    UE cooked format convention: bytecode buffers in the BPGC script_serial_region
    are in the same order as Function exports in the export table.

    Args:
        bytecode_buffers: Dict of {index_str: bytecode_bytes} from extract_bpgc_bytecode
        function_exports: List of all ObjectExport entries from the package
        name_map: Name table (unused for ordinal mapping, kept for API consistency)
        import_map: Import table for class resolution
        export_map: Export table for class resolution
        metrics: Optional BPGCExtractionMetrics to update with mapping results

    Returns:
        Dict mapping function_name to bytecode_bytes.
        Empty dict if no matching functions/buffers.
    """
    from uasset_read.serializers.object_resources import resolve_class_name

    # Step 2: Filter to Function-type exports only
    function_type_exports = [
        exp for exp in function_exports
        if resolve_class_name(exp.class_index, import_map, export_map) in ("Function", "UFunction")
    ]

    if not function_type_exports:
        logger.debug("No Function exports found in export table")
        if metrics is not None:
            metrics.mapping_mismatch = True
        return {}

    # Sort buffers by index key for deterministic ordinal pairing
    sorted_indices = sorted(bytecode_buffers.keys(), key=lambda k: int(k))
    buffer_list = [bytecode_buffers[i] for i in sorted_indices]

    buf_count = len(buffer_list)
    func_count = len(function_type_exports)

    # Step 5: Log warning on count mismatch
    if buf_count != func_count:
        logger.debug(
            "Bytecode/function count mismatch: %d buffers vs %d Function exports — "
            "mapping by min count",
            buf_count, func_count,
        )
        if metrics is not None:
            metrics.mapping_mismatch = True

    # Step 3: Pair by ordinal position
    pair_count = min(buf_count, func_count)
    result = {}
    for i in range(pair_count):
        func_export = function_type_exports[i]
        func_name = func_export.object_name
        result[func_name] = buffer_list[i]

    if metrics is not None:
        metrics.mapped_function_count = len(result)

    logger.info("Mapped %d bytecode buffers to Function exports", len(result))
    return result


# ===========================================================================
# Confidence Validation (#426)
# ===========================================================================


def validate_recovered_bytecode(
    bytecode_bytes: bytes,
    metrics: BPGCExtractionMetrics | None = None,
    function_name: str = "",
) -> tuple[BytecodeConfidenceLevel, list[str]]:
    """Validate recovered bytecode confidence.

    Performs multiple heuristic checks on extracted bytecode, returns confidence
    level and warning list.

    Checks:
    - Empty check
    - Minimum length validity (at least EX_EndOfScript sentinel)
    - Starting token validity
    - Trailing sentinel check
    - Combined assessment with BPGCExtractionMetrics extraction quality

    Args:
        bytecode_bytes: Raw bytes of bytecode to validate
        metrics: Optional BPGCExtractionMetrics from the extraction phase
        function_name: Function name (for log context only)

    Returns:
        Tuple of (confidence_level, warnings):
        - confidence_level: BytecodeConfidenceLevel enum value
        - warnings: Warning message list
    """
    warnings: list[str] = []

    # Empty bytecode
    if not bytecode_bytes:
        return BytecodeConfidenceLevel.UNRECOVERABLE, ["Bytecode is empty"]

    data_len = len(bytecode_bytes)

    # Minimum length check: at least 2 bytes (one token + EX_EndOfScript)
    if data_len < 2:
        warnings.append(f"Bytecode too short ({data_len} bytes), cannot contain valid expressions")
        return BytecodeConfidenceLevel.UNRECOVERABLE, warnings

    # Starting token check
    first_byte = bytecode_bytes[0]
    if first_byte in (0x00, 0xFF):
        warnings.append(f"Starting token 0x{first_byte:02X} is a fill value, bytecode may be corrupt")

    # Trailing sentinel check
    last_byte = bytecode_bytes[-1]
    has_valid_sentinel = last_byte in (_END_OF_SCRIPT, _COOKED_END_SENTINEL)
    if not has_valid_sentinel:
        warnings.append(
            f"Trailing byte 0x{last_byte:02X} is not the expected EX_EndOfScript(0x53) "
            f"or Cooked sentinel(0xDD)"
        )

    # Size reasonableness check: single function bytecode should not exceed 64KB (common Blueprint function limit)
    if data_len > 65536:
        warnings.append(f"Bytecode size {data_len} bytes is abnormally large, may contain non-code data")

    # Combined assessment with metrics
    if metrics is not None:
        if metrics.truncated_buffer_count > 0:
            warnings.append(
                f"{metrics.truncated_buffer_count} buffer(s) were truncated during extraction"
            )
        if metrics.sentinel_mismatch_count > 0:
            warnings.append(
                f"{metrics.sentinel_mismatch_count} buffer(s) had sentinel mismatch during extraction"
            )
        if metrics.mapping_mismatch:
            warnings.append("Buffer count mismatches function export count")

    # Combined confidence assessment
    if not has_valid_sentinel and any("truncat" in w.lower() for w in warnings):
        confidence = BytecodeConfidenceLevel.LOW
    elif not has_valid_sentinel or any("truncat" in w.lower() for w in warnings):
        confidence = BytecodeConfidenceLevel.MEDIUM
    elif warnings:
        confidence = BytecodeConfidenceLevel.MEDIUM
    else:
        confidence = BytecodeConfidenceLevel.HIGH

    if function_name and warnings:
        logger.debug(
            "validate_recovered_bytecode('%s'): confidence=%s, %d warnings",
            function_name, confidence.value, len(warnings),
        )

    return confidence, warnings

