"""
Core data models — UE Blueprint graph containers, nodes, pins, blueprint metadata, and ParseResult.

Exported flat (D-03), callers use ``from uasset_read.models import UEdGraph`` etc.
"""

from .core import (
    FEdGraphPinType,
    UEdGraphPin,
    UEdGraphNode,
    UEdGraph,
    FMemberReference,
)
from .node_types import (
    K2NodeCallFunction,
    K2NodeEvent,
    K2NodeKnot,
    EdGraphNodeComment,
    K2NodeEnhancedInputAction,
    K2NodeFunctionEntry,
)
from .result import (
    BaseResult,
    ParseResult,
    StatusInfo,
)
from .blueprint import (
    BlueprintMetadata,
    BlueprintVariable,
    BlueprintFunction,
    BlueprintEvent,
    BlueprintInterface,
    FunctionParameter,
    MulticastDelegate,
)
from .properties import (
    PropertyTag,
    PropertyTypeName,
    PropertyValue,
    SoftObjectPathValue,
    AdvancedPropertyValue,
    StructValue,
    MapValue,
    SetValue,
    EnumValue,
    TextValue,
    DelegateValue,
)
from .transforms import (
    VectorValue,
    RotatorValue,
    ScaleValue,
    format_transform_value,
)
from .ir import (
    PackageHeaderIR,
    PinIR,
    NodeIR,
    GraphIR,
    PropertyIR,
    ExportIR,
    ExportRawIR,
    ExportDependencyIR,
    ImportIR,
    LinkerSummaryIR,
    PackageIR,
    BlueprintFunctionIR,
    BlueprintEventIR,
    BlueprintIR,
    DecompiledFunctionIR,
    ExecutionChainIR,
    FunctionGraphIR,
    VariableIR,
    SourceSiteContextIR,
    GatherableTextDataIR,
    HexViewEntryIR,
    DebugIR,
    AnimationDataIR,
    PackageDependenciesIR,
    DiagnosticsDataIR,
)
from .ir_anim import (
    AnimNotifyIR,
    AnimBlueprintIR,
    AnimSequenceIR,
    AnimMontageIR,
    BakedExitTransitionIR,
    BakedStateIR,
    BakedTransitionIR,
    BakedStateMachineIR,
)
from .fallback import (
    PropertyFallback,
    StructFallback,
    GenericUObject,
    ExportParseStatus,
    FallbackReason,
)
from .diagnostics import (
    OffsetRangeDiagnostic,
    StructuredDiagnostic,
    DIAGNOSTIC_CODE_NAME_INDEX_OUT_OF_RANGE,
    DIAGNOSTIC_CODE_FSTRING_ALL_NULL,
    DIAGNOSTIC_CODE_FSTRING_LENGTH_EXCEEDS_LIMIT,
    DIAGNOSTIC_CODE_INVALID_SERIAL_SIZE,
    DIAGNOSTIC_CODE_UNKNOWN_SERIALIZATION_CONTROL_BITS,
)

__all__ = [
    # Core models (models/core.py)
    "FEdGraphPinType",
    "UEdGraphPin",
    "UEdGraphNode",
    "UEdGraph",
    "FMemberReference",
    # Node types (node_types.py)
    "K2NodeCallFunction",
    "K2NodeEvent",
    "K2NodeKnot",
    "EdGraphNodeComment",
    "K2NodeEnhancedInputAction",
    "K2NodeFunctionEntry",
    # Result (result.py)
    "BaseResult",
    "ParseResult",
    "StatusInfo",
    # Blueprint metadata (blueprint.py)
    "BlueprintMetadata",
    "BlueprintVariable",
    "BlueprintFunction",
    "BlueprintEvent",
    "BlueprintInterface",
    "FunctionParameter",
    "MulticastDelegate",
    # Property data models
    "PropertyTag",
    "PropertyTypeName",
    "PropertyValue",
    "SoftObjectPathValue",
    "AdvancedPropertyValue",
    "StructValue",
    "MapValue",
    "SetValue",
    "EnumValue",
    "TextValue",
    "DelegateValue",
    # Transform data classes
    "VectorValue",
    "RotatorValue",
    "ScaleValue",
    "format_transform_value",
    # IR intermediate representation (ir.py)
    "PackageHeaderIR",
    "PinIR",
    "NodeIR",
    "GraphIR",
    "PropertyIR",
    "ExportIR",
    "ExportRawIR",
    "ExportDependencyIR",
    "ImportIR",
    "LinkerSummaryIR",
    "PackageIR",
    "BlueprintFunctionIR",
    "BlueprintEventIR",
    "BlueprintIR",
    "DecompiledFunctionIR",
    "ExecutionChainIR",
    "FunctionGraphIR",
    "VariableIR",
    "SourceSiteContextIR",
    "GatherableTextDataIR",
    "HexViewEntryIR",
    "DebugIR",
    "AnimationDataIR",
    "PackageDependenciesIR",
    "DiagnosticsDataIR",
    # Animation IR (ir_anim.py)
    "AnimNotifyIR",
    "AnimBlueprintIR",
    "AnimSequenceIR",
    "AnimMontageIR",
    "BakedExitTransitionIR",
    "BakedStateIR",
    "BakedTransitionIR",
    "BakedStateMachineIR",
    # Fallback models
    "PropertyFallback",
    "StructFallback",
    "GenericUObject",
    "ExportParseStatus",
    "FallbackReason",
    # Diagnostic models
    "OffsetRangeDiagnostic",
    "StructuredDiagnostic",
    "DIAGNOSTIC_CODE_NAME_INDEX_OUT_OF_RANGE",
    "DIAGNOSTIC_CODE_FSTRING_ALL_NULL",
    "DIAGNOSTIC_CODE_FSTRING_LENGTH_EXCEEDS_LIMIT",
    "DIAGNOSTIC_CODE_INVALID_SERIAL_SIZE",
    "DIAGNOSTIC_CODE_UNKNOWN_SERIALIZATION_CONTROL_BITS",
]
